import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'your@email.com' }).click();
  await page.getByRole('textbox', { name: 'your@email.com' }).fill('test1@gmail.com');
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).fill('123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Register here' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).fill('test 1');
  await page.getByRole('textbox', { name: 'your@email.com' }).click();
  await page.getByRole('textbox', { name: 'your@email.com' }).fill('test1@gmail.com');
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).fill('12332fdvedavd');
  await page.getByRole('textbox', { name: '••••••••' }).dblclick();
  await page.getByRole('textbox', { name: '••••••••' }).fill('Password');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('link', { name: 'My Items' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'Browse', exact: true }).click();
  await page.getByRole('link', { name: 'View' }).first().click();
  await page.getByRole('textbox', { name: 'Optional message…' }).click();
  await page.getByRole('link', { name: 'Create Listing' }).click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('Test');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('test');
  await page.getByRole('combobox').first().selectOption('fashion');
  await page.getByRole('combobox').nth(1).selectOption('new');
  await page.getByRole('textbox', { name: 'Location' }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('A conceptual graphic showing a deep learning network learning from raw data and generating complex representations, contrasted with a traditional model relying on pre-defined features..png');
  await page.getByRole('button', { name: 'Create Listing' }).click();
  await page.getByRole('link', { name: 'Test Test available test' }).click();
  await page.getByRole('link', { name: 'Edit Item' }).click();
  await page.getByRole('combobox').nth(1).selectOption('like-new');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('link', { name: 'Browse', exact: true }).click();
  await page.getByRole('link', { name: 'View' }).nth(2).click();
  await page.getByRole('button', { name: 'Test', exact: true }).click();
  await page.getByRole('button', { name: 'Test', exact: true }).click();
  await page.getByRole('button', { name: 'Test', exact: true }).click();
  await page.getByRole('textbox', { name: 'Optional message…' }).click();
  await page.getByRole('textbox', { name: 'Optional message…' }).fill('Hi lets trade');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Send Offer' }).click();
  await page.goto('http://localhost:5173/listings/693ec5955815a1190e1c878d');
  await page.getByRole('button', { name: 'My Messages' }).click();
  await page.getByRole('button', { name: 'Their Messages' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
});